import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import { Element } from "react-scroll";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Element name='main' className='element'>
        <Main/>
      </Element>
      
      <Element name='about' className='element'>
        <About/>
      </Element>

      <Element name='skills' className='element'>
        <Skills/>
      </Element>

      <Element name='projects' className='element'>
        <Projects/>
      </Element>

      <Element name='contact' className='element'>
        <Contact/>
      </Element>
    </div>
  )
}

export default Home
